CREATE TABLE IF NOT EXISTS `users` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `sLogin` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `sOpenIdIdentity` varchar(255) DEFAULT NULL COMMENT 'User''s Open Id Identity',
  `sPasswordMd5` varchar(100) NOT NULL,
  `sSalt` varchar(32) NOT NULL,
  `sRecover` varchar(50) NOT NULL,
  `sRegistrationDate` date NOT NULL DEFAULT '0000-00-00',
  `sEmail` varchar(100) NOT NULL,
  `bEmailVerified` tinyint(1) NOT NULL,
  `sFirstName` varchar(100) NOT NULL COMMENT 'User''s first name',
  `sLastName` varchar(100) NOT NULL COMMENT 'User''s last name',
  `sCountryCode` char(3) NOT NULL DEFAULT '',
  `sTimeZone` varchar(100) NOT NULL,
  `sBirthDate` date NOT NULL DEFAULT '0000-00-00' COMMENT 'User''s birth date',
  `iGraduationYear` int(11) NOT NULL DEFAULT '0' COMMENT 'User''s high school graduation year',
  `sSex` enum('Male','Female') DEFAULT NULL,
  `sAddress` mediumtext NOT NULL COMMENT 'User''s address',
  `sZipcode` longtext NOT NULL COMMENT 'User''s postal code',
  `sCity` longtext NOT NULL COMMENT 'User''s city',
  `sLandLineNumber` longtext NOT NULL COMMENT 'User''s phone number',
  `sCellPhoneNumber` longtext NOT NULL COMMENT 'User''s mobil phone number',
  `sDefaultLanguage` char(3) NOT NULL DEFAULT 'fr' COMMENT 'User''s default language',
  `bNotifyNews` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'TODO',
  `iNotify` tinyint(4) NOT NULL,
  `bPublicFirstName` tinyint(4) NOT NULL COMMENT 'Publicly show user''s first name',
  `bPublicLastName` tinyint(4) NOT NULL COMMENT 'Publicly show user''s first name',
  `sFreeText` mediumtext NOT NULL,
  `sWebSite` varchar(100) NOT NULL,
  `bPhotoAutoload` tinyint(1) NOT NULL DEFAULT '0',
  `sLangProg` varchar(30) DEFAULT 'Python',
  `sLastLoginDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `sLastActivityDate` datetime DEFAULT NULL COMMENT 'User''s last activity time on the website',
  `sLastIP` varchar(16) NOT NULL,
  `bBasicEditorMode` tinyint(4) NOT NULL DEFAULT '1',
  `nbSpacesForTab` int(11) NOT NULL DEFAULT '3',
  `iMemberState` tinyint(4) NOT NULL DEFAULT '0',
  `idUserGodfather` int(11) DEFAULT NULL,
  `iStepLevelInSite` int(11) NOT NULL COMMENT 'User''s level',
  `bIsTrainer` tinyint(4) NOT NULL DEFAULT '0',
  `bNoRanking` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'TODO',
  `nbHelpGiven` int(11) NOT NULL COMMENT 'TODO',
  `iVersion` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `sLogin` (`sLogin`(20)),
  KEY `iVersion` (`iVersion`),
  KEY `sCountryCode` (`sCountryCode`),
  KEY `idUserGodfather` (`idUserGodfather`),
  KEY `sLangProg` (`sLangProg`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `history_users` (
  `historyID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` bigint(20) NOT NULL,
  `sLogin` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `sOpenIdIdentity` varchar(255) DEFAULT NULL COMMENT 'User''s Open Id Identity',
  `sPasswordMd5` varchar(100) NOT NULL,
  `sSalt` varchar(32) NOT NULL,
  `sRecover` varchar(50) NOT NULL,
  `sRegistrationDate` date NOT NULL DEFAULT '0000-00-00',
  `sEmail` varchar(100) NOT NULL,
  `bEmailVerified` tinyint(1) NOT NULL,
  `sFirstName` varchar(100) NOT NULL COMMENT 'User''s first name',
  `sLastName` varchar(100) NOT NULL COMMENT 'User''s last name',
  `sCountryCode` char(3) NOT NULL DEFAULT '',
  `sTimeZone` varchar(100) NOT NULL,
  `sBirthDate` date NOT NULL DEFAULT '0000-00-00' COMMENT 'User''s birth date',
  `iGraduationYear` int(11) NOT NULL DEFAULT '0' COMMENT 'User''s high school graduation year',
  `sSex` enum('Male','Female') DEFAULT NULL,
  `sAddress` mediumtext NOT NULL COMMENT 'User''s address',
  `sZipcode` longtext NOT NULL COMMENT 'User''s postal code',
  `sCity` longtext NOT NULL COMMENT 'User''s city',
  `sLandLineNumber` longtext NOT NULL COMMENT 'User''s phone number',
  `sCellPhoneNumber` longtext NOT NULL COMMENT 'User''s mobil phone number',
  `sDefaultLanguage` char(3) NOT NULL DEFAULT 'fr' COMMENT 'User''s default language',
  `bNotifyNews` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'TODO',
  `iNotify` tinyint(4) NOT NULL,
  `bPublicFirstName` tinyint(4) NOT NULL COMMENT 'Publicly show user''s first name',
  `bPublicLastName` tinyint(4) NOT NULL COMMENT 'Publicly show user''s first name',
  `sFreeText` mediumtext NOT NULL,
  `sWebSite` varchar(100) NOT NULL,
  `bPhotoAutoload` tinyint(1) NOT NULL DEFAULT '0',
  `sLangProg` varchar(30) DEFAULT 'Python',
  `sLastLoginDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `sLastActivityDate` datetime DEFAULT NULL COMMENT 'User''s last activity time on the website',
  `sLastIP` varchar(16) NOT NULL,
  `bBasicEditorMode` tinyint(4) NOT NULL DEFAULT '1',
  `nbSpacesForTab` int(11) NOT NULL DEFAULT '3',
  `iMemberState` tinyint(4) NOT NULL DEFAULT '0',
  `idUserGodfather` int(11) DEFAULT NULL,
  `iStepLevelInSite` int(11) NOT NULL COMMENT 'User''s level',
  `bIsTrainer` tinyint(4) NOT NULL DEFAULT '0',
  `bNoRanking` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'TODO',
  `nbHelpGiven` int(11) NOT NULL COMMENT 'TODO',
  `iVersion` int(11) NOT NULL,
  `iNextVersion` int(11) NOT NULL,
  `bDeleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`historyID`),
  KEY `ID` (`ID`),
  UNIQUE KEY `sLogin` (`sLogin`(20)),
  KEY `iVersion` (`iVersion`),
  KEY `sCountryCode` (`sCountryCode`),
  KEY `idUserGodfather` (`idUserGodfather`),
  KEY `sLangProg` (`sLangProg`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



