CREATE TABLE IF NOT EXISTS `users_items` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `idUser` bigint(20) NOT NULL,
  `idItem` bigint(20) NOT NULL,
  `iScore` int(11) NOT NULL,
  `iScoreComputed` int(11) NOT NULL,
  `iScoreDiffManual` int(11) NOT NULL,
  `sScoreDiffComment` varchar(200) NOT NULL,
  `nbSubmissionsAttempts` int(11) NOT NULL,
  `nbTasksTried` int(11) NOT NULL,
  `nbTasksSolved` int(11) NOT NULL,
  `nbChildrenValidated` int(11) NOT NULL,
  `bValidated` int(11) NOT NULL,
  `bFinished` int(11) NOT NULL,
  `nbTasksWithHelp` int(11) NOT NULL,
  `nbHintsCached` int(11) NOT NULL,
  `nbCorrectionsRead` int(11) NOT NULL,
  `iPrecision` int(11) NOT NULL,
  `iAutonomy` int(11) NOT NULL,
  `sStartDate` datetime NOT NULL,
  `sValidationDate` datetime NOT NULL,
  `sFinishDate` datetime NOT NULL,
  `sLastActivityDate` datetime NOT NULL,
  `bRanked` tinyint(1) NOT NULL,
  `sAllLangProg` varchar(200) NOT NULL,
  `iVersion` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `iVersion` (`iVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `history_users_items` (
  `historyID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` bigint(20) NOT NULL,
  `idUser` bigint(20) NOT NULL,
  `idItem` bigint(20) NOT NULL,
  `iScore` int(11) NOT NULL,
  `iScoreComputed` int(11) NOT NULL,
  `iScoreDiffManual` int(11) NOT NULL,
  `sScoreDiffComment` varchar(200) NOT NULL,
  `nbSubmissionsAttempts` int(11) NOT NULL,
  `nbTasksTried` int(11) NOT NULL,
  `nbTasksSolved` int(11) NOT NULL,
  `nbChildrenValidated` int(11) NOT NULL,
  `bValidated` int(11) NOT NULL,
  `bFinished` int(11) NOT NULL,
  `nbTasksWithHelp` int(11) NOT NULL,
  `nbHintsCached` int(11) NOT NULL,
  `nbCorrectionsRead` int(11) NOT NULL,
  `iPrecision` int(11) NOT NULL,
  `iAutonomy` int(11) NOT NULL,
  `sStartDate` datetime NOT NULL,
  `sValidationDate` datetime NOT NULL,
  `sFinishDate` datetime NOT NULL,
  `sLastActivityDate` datetime NOT NULL,
  `bRanked` tinyint(1) NOT NULL,
  `sAllLangProg` varchar(200) NOT NULL,
  `iVersion` int(11) NOT NULL,
  `iNextVersion` int(11) NOT NULL,
  `bDeleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`historyID`),
  KEY `ID` (`ID`),
  KEY `iVersion` (`iVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
